# Customer Churn Prediction Modelling

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pip install tensorflow[and-cuda]

Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.20.0-cp311-cp311-win_amd64.whl.metadata (4.6 kB)
Collecting absl-py>=1.0.0 (from tensorflow[and-cuda])
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow[and-cuda])
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow[and-cuda])
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow[and-cuda])
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow[and-cuda])
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow[and-cuda])
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow[and-cuda])
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow[and-cuda]) (25.0)
Collecting protobuf>=5.28.0 (from tensorflow[and-cuda])
  Downloading protobuf-6.33.5-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow[and-cuda]) (2.32.5)
Requirement already satisfied: setuptools in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow[and-cuda]) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow[and-cuda]) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow[and-cuda])
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow[and-cuda]) (4.15.0)
Collecting wrapt>=1.11.0 (from tensorflow[and-cuda])
  Downloading wrapt-2.1.1-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow[and-cuda])
  Downloading grpcio-1.76.0-cp311-cp311-win_amd64.whl.metadata (3.8 kB)
Collecting tensorboard~=2.20.0 (from tensorflow[and-cuda])
  Downloading tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting keras>=3.10.0 (from tensorflow[and-cuda])
  Downloading keras-3.13.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow[and-cuda]) (2.4.0)
Collecting h5py>=3.11.0 (from tensorflow[and-cuda])
  Downloading h5py-3.15.1-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow[and-cuda])
  Downloading ml_dtypes-0.5.4-cp311-cp311-win_amd64.whl.metadata (9.2 kB)
Collecting nvidia-cublas-cu12<13.0,>=12.5.3.2 (from tensorflow[and-cuda])
  Downloading nvidia_cublas_cu12-12.9.1.4-py3-none-win_amd64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12<13.0,>=12.5.82 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_cupti_cu12-12.9.79-py3-none-win_amd64.whl.metadata (1.8 kB)
Collecting nvidia-cuda-nvcc-cu12<13.0,>=12.5.82 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_nvcc_cu12-12.9.86-py3-none-win_amd64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-nvrtc-cu12<13.0,>=12.5.82 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_nvrtc_cu12-12.9.86-py3-none-win_amd64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12<13.0,>=12.5.82 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_runtime_cu12-12.9.79-py3-none-win_amd64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12<10.0,>=9.3.0.75 (from tensorflow[and-cuda])
  Downloading nvidia_cudnn_cu12-9.19.0.56-py3-none-win_amd64.whl.metadata (1.9 kB)
Collecting nvidia-cufft-cu12<12.0,>=11.2.3.61 (from tensorflow[and-cuda])
  Downloading nvidia_cufft_cu12-11.4.1.4-py3-none-win_amd64.whl.metadata (1.8 kB)
Collecting nvidia-curand-cu12<11.0,>=10.3.6.82 (from tensorflow[and-cuda])
  Downloading nvidia_curand_cu12-10.3.10.19-py3-none-win_amd64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12<12.0,>=11.6.3.83 (from tensorflow[and-cuda])
  Downloading nvidia_cusolver_cu12-11.7.5.82-py3-none-win_amd64.whl.metadata (1.9 kB)
Collecting nvidia-cusparse-cu12<13.0,>=12.5.1.3 (from tensorflow[and-cuda])
  Downloading nvidia_cusparse_cu12-12.5.10.65-py3-none-win_amd64.whl.metadata (1.8 kB)
INFO: pip is looking at multiple versions of tensorflow[and-cuda] to determine which version is compatible with other requirements. This could take a while.
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.19.1-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 (from tensorflow[and-cuda])
  Downloading protobuf-5.29.5-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Collecting tensorboard~=2.19.0 (from tensorflow[and-cuda])
  Downloading tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
Collecting numpy<2.2.0,>=1.26.0 (from tensorflow[and-cuda])
  Downloading numpy-2.1.3-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow[and-cuda])
  Downloading tensorflow_io_gcs_filesystem-0.31.0-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting nvidia-cublas-cu12==12.5.3.2 (from tensorflow[and-cuda])
  Downloading nvidia_cublas_cu12-12.5.3.2-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.5.82 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_cupti_cu12-12.5.82-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting nvidia-cuda-nvcc-cu12==12.5.82 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_nvcc_cu12-12.5.82-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.5.82 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_nvrtc_cu12-12.5.82-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.5.82 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_runtime_cu12-12.5.82-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cudnn-cu12==9.3.0.75 (from tensorflow[and-cuda])
  Downloading nvidia_cudnn_cu12-9.3.0.75-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting nvidia-cufft-cu12==11.2.3.61 (from tensorflow[and-cuda])
  Downloading nvidia_cufft_cu12-11.2.3.61-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.6.82 (from tensorflow[and-cuda])
  Downloading nvidia_curand_cu12-10.3.6.82-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.3.83 (from tensorflow[and-cuda])
  Downloading nvidia_cusolver_cu12-11.6.3.83-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.5.1.3 (from tensorflow[and-cuda])
  Downloading nvidia_cusparse_cu12-12.5.1.3-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.19.0-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
  Downloading tensorflow-2.18.1-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting tensorboard<2.19,>=2.18 (from tensorflow[and-cuda])
  Downloading tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Collecting numpy<2.1.0,>=1.26.0 (from tensorflow[and-cuda])
  Downloading numpy-2.0.2-cp311-cp311-win_amd64.whl.metadata (59 kB)
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.18.0-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
Collecting tensorflow-intel==2.18.0 (from tensorflow[and-cuda])
  Downloading tensorflow_intel-2.18.0-cp311-cp311-win_amd64.whl.metadata (4.9 kB)
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.17.1-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
Collecting tensorflow-intel==2.17.1 (from tensorflow[and-cuda])
  Downloading tensorflow_intel-2.17.1-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
Collecting nvidia-cublas-cu12==12.3.4.1 (from tensorflow[and-cuda])
  Downloading nvidia_cublas_cu12-12.3.4.1-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.3.101 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_cupti_cu12-12.3.101-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting nvidia-cuda-nvcc-cu12==12.3.107 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_nvcc_cu12-12.3.107-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.3.107 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_nvrtc_cu12-12.3.107-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.3.101 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_runtime_cu12-12.3.101-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cudnn-cu12==8.9.7.29 (from tensorflow[and-cuda])
  Downloading nvidia_cudnn_cu12-8.9.7.29-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting nvidia-cufft-cu12==11.0.12.1 (from tensorflow[and-cuda])
  Downloading nvidia_cufft_cu12-11.0.12.1-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.4.107 (from tensorflow[and-cuda])
  Downloading nvidia_curand_cu12-10.3.4.107-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.5.4.101 (from tensorflow[and-cuda])
  Downloading nvidia_cusolver_cu12-11.5.4.101-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.2.0.103 (from tensorflow[and-cuda])
  Downloading nvidia_cusparse_cu12-12.2.0.103-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.17.0-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
Collecting tensorflow-intel==2.17.0 (from tensorflow[and-cuda])
  Downloading tensorflow_intel-2.17.0-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.16.2-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
Collecting tensorflow-intel==2.16.2 (from tensorflow[and-cuda])
  Downloading tensorflow_intel-2.16.2-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
INFO: pip is still looking at multiple versions of tensorflow[and-cuda] to determine which version is compatible with other requirements. This could take a while.
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.16.1-cp311-cp311-win_amd64.whl.metadata (3.5 kB)
Collecting tensorflow-intel==2.16.1 (from tensorflow[and-cuda])
  Downloading tensorflow_intel-2.16.1-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.15.1-cp311-cp311-win_amd64.whl.metadata (3.4 kB)
Collecting tensorflow-intel==2.15.1 (from tensorflow[and-cuda])
  Downloading tensorflow_intel-2.15.1-cp311-cp311-win_amd64.whl.metadata (4.9 kB)
Collecting nvidia-cublas-cu12==12.2.5.6 (from tensorflow[and-cuda])
  Downloading nvidia_cublas_cu12-12.2.5.6-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.2.142 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_cupti_cu12-12.2.142-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting nvidia-cuda-nvcc-cu12==12.2.140 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_nvcc_cu12-12.2.140-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.2.140 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_nvrtc_cu12-12.2.140-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.2.140 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_runtime_cu12-12.2.140-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cudnn-cu12==8.9.4.25 (from tensorflow[and-cuda])
  Downloading nvidia_cudnn_cu12-8.9.4.25-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting nvidia-cufft-cu12==11.0.8.103 (from tensorflow[and-cuda])
  Downloading nvidia_cufft_cu12-11.0.8.103-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.3.141 (from tensorflow[and-cuda])
  Downloading nvidia_curand_cu12-10.3.3.141-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.5.2.141 (from tensorflow[and-cuda])
  Downloading nvidia_cusolver_cu12-11.5.2.141-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.2.141 (from tensorflow[and-cuda])
  Downloading nvidia_cusparse_cu12-12.1.2.141-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.15.0-cp311-cp311-win_amd64.whl.metadata (3.6 kB)
Collecting tensorflow-intel==2.15.0 (from tensorflow[and-cuda])
  Downloading tensorflow_intel-2.15.0-cp311-cp311-win_amd64.whl.metadata (5.1 kB)
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.14.1-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
Collecting tensorflow-intel==2.14.1 (from tensorflow[and-cuda])
  Downloading tensorflow_intel-2.14.1-cp311-cp311-win_amd64.whl.metadata (4.8 kB)
Collecting nvidia-cublas-cu11==11.11.3.6 (from tensorflow[and-cuda])
  Downloading nvidia_cublas_cu11-11.11.3.6-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu11==11.8.87 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_cupti_cu11-11.8.87-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting nvidia-cuda-nvcc-cu11==11.8.89 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_nvcc_cu11-11.8.89-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu11==11.8.89 (from tensorflow[and-cuda])
  Downloading nvidia_cuda_runtime_cu11-11.8.89-py3-none-win_amd64.whl.metadata (1.5 kB)
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.14.0-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
Collecting tensorflow-intel==2.14.0 (from tensorflow[and-cuda])
  Downloading tensorflow_intel-2.14.0-cp311-cp311-win_amd64.whl.metadata (4.8 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
Collecting tensorflow[and-cuda]
  Downloading tensorflow-2.13.1-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Collecting tensorflow-intel==2.13.1 (from tensorflow[and-cuda])
  Downloading tensorflow_intel-2.13.1-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting gast<=0.4.0,>=0.2.1 (from tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
Collecting numpy<=1.24.3,>=1.22 (from tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading numpy-1.24.3-cp311-cp311-win_amd64.whl.metadata (5.6 kB)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading protobuf-4.25.8-cp310-abi3-win_amd64.whl.metadata (541 bytes)
Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
Collecting tensorboard<2.14,>=2.13 (from tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting keras<2.14,>=2.13.1 (from tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
INFO: pip is looking at multiple versions of grpcio to determine which version is compatible with other requirements. This could take a while.
Collecting grpcio<2.0,>=1.24.3 (from tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading grpcio-1.75.1-cp311-cp311-win_amd64.whl.metadata (3.8 kB)
  Downloading grpcio-1.75.0-cp311-cp311-win_amd64.whl.metadata (3.8 kB)
  Downloading grpcio-1.74.0-cp311-cp311-win_amd64.whl.metadata (4.0 kB)
Collecting google-auth<3,>=1.6.3 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading google_auth-2.48.0-py3-none-any.whl.metadata (6.2 kB)
Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting markdown>=2.6.8 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading markdown-3.10.1-py3-none-any.whl.metadata (5.1 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading werkzeug-3.1.5-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: wheel>=0.26 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda]) (0.45.1)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting cryptography>=38.0.3 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading cryptography-46.0.4-cp311-abi3-win_amd64.whl.metadata (5.7 kB)
Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow[and-cuda]) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow[and-cuda]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow[and-cuda]) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow[and-cuda]) (2025.11.12)
Collecting pyasn1>=0.1.3 (from rsa<5,>=3.1.4->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading pyasn1-0.6.2-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: cffi>=2.0.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda]) (2.0.0)
Requirement already satisfied: pycparser in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda]) (2.23)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda])
  Downloading oauthlib-3.3.1-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.14,>=2.13->tensorflow-intel==2.13.1->tensorflow[and-cuda]) (3.0.3)
Downloading tensorflow-2.13.1-cp311-cp311-win_amd64.whl (1.9 kB)
Downloading tensorflow_intel-2.13.1-cp311-cp311-win_amd64.whl (276.6 MB)
   ---------------------------------------- 0.0/276.6 MB ? eta -:--:--

WARNING: tensorflow 2.13.1 does not provide the extra 'and-cuda'
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\OneDrive\Desktop\Machine-Learning\.venv\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\OneDrive\Desktop\Machine-Learning\.venv\Lib\site-packages\~umpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.3.3 requires numpy>=1.25, but you have numpy 1.24.3 which is incompatible.
ipython 9.8.0 requires typing_extensions>=4.6; python_version < "3.12", but you have typing-extensions 4.5.0 which is incompatible.
scipy 1.16.3 requires numpy<2.6,>=1.25.2, but you have numpy 1.24.3 which is incompatible.

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
pip install --upgrade tensorflow

Requirement already satisfied: tensorflow in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (2.13.1)
Collecting tensorflow
  Using cached tensorflow-2.20.0-cp311-cp311-win_amd64.whl.metadata (4.6 kB)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (0.4.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (25.0)
Collecting protobuf>=5.28.0 (from tensorflow)
  Using cached protobuf-6.33.5-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (4.5.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (1.74.0)
Collecting tensorboard~=2.20.0 (from tensorflow)
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting keras>=3.10.0 (from tensorflow)
  Using cached keras-3.13.2-py3-none-any.whl.metadata (6.3 kB)
Collecting numpy>=1.26.0 (from tensorflow)
  Downloading numpy-2.4.2-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: h5py>=3.11.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow) (3.15.1)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Using cached ml_dtypes-0.5.4-cp311-cp311-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.11.12)
Requirement already satisfied: markdown>=2.6.8 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.10.1)
Requirement already satisfied: pillow in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (12.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.1.5)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Collecting rich (from keras>=3.10.0->tensorflow)
  Downloading rich-14.3.2-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.10.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.10.0->tensorflow)
  Downloading optree-0.18.0-cp311-cp311-win_amd64.whl.metadata (35 kB)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Collecting typing_extensions>=3.6.6 (from tensorflow)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.10.0->tensorflow)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.20.0-cp311-cp311-win_amd64.whl (331.8 MB)
   ---------------------------------------- 0.0/331.8 MB ? eta -:--:--
   ---------------------------------------- 0.3/331.8 MB ? eta -:--:--
   ---------------------------------------- 0.5/331.8 MB 1.3 MB/s eta 0:04:18
   ---------------------------------------- 0.8/331.8 MB 1.3 MB/s eta 0:04:17
   ---------------------------------------- 1.0/331.8 MB 1.3 MB/s eta 0:04:17
   ---------------------------------------- 1.3/331.8 MB 1.3 MB/s eta 0:04:17
   ---------------------------------------- 1.6/331.8 MB 1.3 MB/s eta 0:04:12
   ---------------------------------------- 1.8/331.8 MB 1.3 MB/s eta 0:04:13
   ---------------------------------------- 2.4/331.8 MB 1.3 MB/s eta 0:04:13
   ---------------------------------------- 2.6/331.8 MB 1.3 MB/s eta 0:04:13
   ---------------------------------------- 2.9/331.8 MB 1.3 MB/s eta 0:04:13
   ---------------------------------------- 3.1/331.8 MB 1.3 MB/s eta 0:04:13
   ---------------------------------------- 3.4/331.8 MB 1.3 MB/s eta 0:04:13
   ---------------------------------------- 3.7/331.8 MB 1.3 MB/s eta 0:04:13
   ---------------------------------------- 3.9/331.8 MB 1.3 MB/s eta 0:04:13
    --------------------------------------- 4.2/331.8 MB 1.3 MB/s eta 0:04:13
    --------------------------------------- 4.5/331.8 MB 1.3 MB/s eta 0:04:13
    --------------------------------------- 4.7/331.8 MB 1.3 MB/s eta 0:04:13
    --------------------------------------- 5.0/331.8 MB 1.3 MB/s eta 0:04:13
    --------------------------------------- 5.2/331.8 MB 1.3 MB/s eta 0:04:12
    --------------------------------------- 5.5/331.8 MB 1.3 MB/s eta 0:04:11
    --------------------------------------- 6.0/331.8 MB 1.3 MB/s eta 0:04:11
    --------------------------------------- 6.3/331.8 MB 1.3 MB/s eta 0:04:11
    --------------------------------------- 6.6/331.8 MB 1.3 MB/s eta 0:04:11
    --------------------------------------- 6.8/331.8 MB 1.3 MB/s eta 0:04:11
    --------------------------------------- 7.1/331.8 MB 1.3 MB/s eta 0:04:11
    --------------------------------------- 7.3/331.8 MB 1.3 MB/s eta 0:04:11
    --------------------------------------- 7.6/331.8 MB 1.3 MB/s eta 0:04:10
    --------------------------------------- 7.9/331.8 MB 1.3 MB/s eta 0:04:10
    --------------------------------------- 8.1/331.8 MB 1.3 MB/s eta 0:04:09
   - -------------------------------------- 8.4/331.8 MB 1.3 MB/s eta 0:04:10
   - -------------------------------------- 8.7/331.8 MB 1.3 MB/s eta 0:04:09
   - -------------------------------------- 8.9/331.8 MB 1.3 MB/s eta 0:04:09
   - -------------------------------------- 9.2/331.8 MB 1.3 MB/s eta 0:04:09
   - -------------------------------------- 9.4/331.8 MB 1.3 MB/s eta 0:04:09
   - -------------------------------------- 9.7/331.8 MB 1.3 MB/s eta 0:04:09
   - -------------------------------------- 10.0/331.8 MB 1.3 MB/s eta 0:04:09
   - -------------------------------------- 10.5/331.8 MB 1.3 MB/s eta 0:04:09
   - -------------------------------------- 10.7/331.8 MB 1.3 MB/s eta 0:04:08
   - -------------------------------------- 11.0/331.8 MB 1.3 MB/s eta 0:04:08
   - -------------------------------------- 11.3/331.8 MB 1.3 MB/s eta 0:04:08
   - -------------------------------------- 11.5/331.8 MB 1.3 MB/s eta 0:04:08
   - -------------------------------------- 11.8/331.8 MB 1.3 MB/s eta 0:04:08
   - -------------------------------------- 12.1/331.8 MB 1.3 MB/s eta 0:04:07
   - -------------------------------------- 12.3/331.8 MB 1.3 MB/s eta 0:04:07
   - -------------------------------------- 12.6/331.8 MB 1.3 MB/s eta 0:04:07
   - -------------------------------------- 12.8/331.8 MB 1.3 MB/s eta 0:04:07
   - -------------------------------------- 13.1/331.8 MB 1.3 MB/s eta 0:04:06
   - -------------------------------------- 13.4/331.8 MB 1.3 MB/s eta 0:04:06
   - -------------------------------------- 13.6/331.8 MB 1.3 MB/s eta 0:04:06
   - -------------------------------------- 14.2/331.8 MB 1.3 MB/s eta 0:04:05
   - -------------------------------------- 14.4/331.8 MB 1.3 MB/s eta 0:04:05
   - -------------------------------------- 14.7/331.8 MB 1.3 MB/s eta 0:04:05
   - -------------------------------------- 14.9/331.8 MB 1.3 MB/s eta 0:04:05
   - -------------------------------------- 15.2/331.8 MB 1.3 MB/s eta 0:04:05
   - -------------------------------------- 15.5/331.8 MB 1.3 MB/s eta 0:04:04
   - -------------------------------------- 15.7/331.8 MB 1.3 MB/s eta 0:04:04
   - -------------------------------------- 16.0/331.8 MB 1.3 MB/s eta 0:04:04
   - -------------------------------------- 16.3/331.8 MB 1.3 MB/s eta 0:04:04
   - -------------------------------------- 16.5/331.8 MB 1.3 MB/s eta 0:04:04
   -- ------------------------------------- 16.8/331.8 MB 1.3 MB/s eta 0:04:03
   -- ------------------------------------- 17.0/331.8 MB 1.3 MB/s eta 0:04:03
   -- ------------------------------------- 17.3/331.8 MB 1.3 MB/s eta 0:04:03
   -- ------------------------------------- 17.6/331.8 MB 1.3 MB/s eta 0:04:03
   -- ------------------------------------- 17.8/331.8 MB 1.3 MB/s eta 0:04:03
   -- ------------------------------------- 18.1/331.8 MB 1.3 MB/s eta 0:04:03
   -- ------------------------------------- 18.6/331.8 MB 1.3 MB/s eta 0:04:02
   -- ------------------------------------- 18.9/331.8 MB 1.3 MB/s eta 0:04:02
   -- ------------------------------------- 19.1/331.8 MB 1.3 MB/s eta 0:04:02
   -- ------------------------------------- 19.4/331.8 MB 1.3 MB/s eta 0:04:02
   -- ------------------------------------- 19.7/331.8 MB 1.3 MB/s eta 0:04:01
   -- ------------------------------------- 19.9/331.8 MB 1.3 MB/s eta 0:04:01
   -- ------------------------------------- 20.2/331.8 MB 1.3 MB/s eta 0:04:01
   -- ------------------------------------- 20.4/331.8 MB 1.3 MB/s eta 0:04:01
   -- ------------------------------------- 20.7/331.8 MB 1.3 MB/s eta 0:04:01
   -- ------------------------------------- 20.7/331.8 MB 1.3 MB/s eta 0:04:01
   -- ------------------------------------- 21.2/331.8 MB 1.3 MB/s eta 0:04:00
   -- ------------------------------------- 21.5/331.8 MB 1.3 MB/s eta 0:04:00
   -- ------------------------------------- 21.8/331.8 MB 1.3 MB/s eta 0:04:00
   -- ------------------------------------- 22.0/331.8 MB 1.3 MB/s eta 0:04:00
   -- ------------------------------------- 22.3/331.8 MB 1.3 MB/s eta 0:04:00
   -- ------------------------------------- 22.5/331.8 MB 1.3 MB/s eta 0:04:00
   -- ------------------------------------- 22.8/331.8 MB 1.3 MB/s eta 0:03:59
   -- ------------------------------------- 23.1/331.8 MB 1.3 MB/s eta 0:03:59
   -- ------------------------------------- 23.6/331.8 MB 1.3 MB/s eta 0:03:59
   -- ------------------------------------- 23.9/331.8 MB 1.3 MB/s eta 0:03:59
   -- ------------------------------------- 24.1/331.8 MB 1.3 MB/s eta 0:03:58
   -- ------------------------------------- 24.4/331.8 MB 1.3 MB/s eta 0:03:58
   -- ------------------------------------- 24.6/331.8 MB 1.3 MB/s eta 0:03:58
   --- ------------------------------------ 24.9/331.8 MB 1.3 MB/s eta 0:03:58
   --- ------------------------------------ 25.2/331.8 MB 1.3 MB/s eta 0:03:57
   --- ------------------------------------ 25.4/331.8 MB 1.3 MB/s eta 0:03:57
   --- ------------------------------------ 25.7/331.8 MB 1.3 MB/s eta 0:03:57
   --- ------------------------------------ 26.0/331.8 MB 1.3 MB/s eta 0:03:57
   --- ------------------------------------ 26.2/331.8 MB 1.3 MB/s eta 0:03:57
   --- ------------------------------------ 26.5/331.8 MB 1.3 MB/s eta 0:03:57
   --- ------------------------------------ 26.7/331.8 MB 1.3 MB/s eta 0:03:56
   --- ------------------------------------ 27.0/331.8 MB 1.3 MB/s eta 0:03:56
   --- ------------------------------------ 27.3/331.8 MB 1.3 MB/s eta 0:03:56
   --- ------------------------------------ 27.5/331.8 MB 1.3 MB/s eta 0:03:56
   --- ------------------------------------ 27.8/331.8 MB 1.3 MB/s eta 0:03:56
   --- ------------------------------------ 28.0/331.8 MB 1.3 MB/s eta 0:03:56
   --- ------------------------------------ 28.3/331.8 MB 1.3 MB/s eta 0:03:56
   --- ------------------------------------ 28.6/331.8 MB 1.3 MB/s eta 0:03:56
   --- ------------------------------------ 28.8/331.8 MB 1.3 MB/s eta 0:03:55
   --- ------------------------------------ 29.1/331.8 MB 1.3 MB/s eta 0:03:55
   --- ------------------------------------ 29.4/331.8 MB 1.3 MB/s eta 0:03:55
   --- ------------------------------------ 29.6/331.8 MB 1.3 MB/s eta 0:03:55
   --- ------------------------------------ 29.9/331.8 MB 1.3 MB/s eta 0:03:55
   --- ------------------------------------ 30.1/331.8 MB 1.3 MB/s eta 0:03:55
   --- ------------------------------------ 30.4/331.8 MB 1.3 MB/s eta 0:03:55
   --- ------------------------------------ 30.7/331.8 MB 1.3 MB/s eta 0:03:54
   --- ------------------------------------ 30.9/331.8 MB 1.3 MB/s eta 0:03:54
   --- ------------------------------------ 31.2/331.8 MB 1.3 MB/s eta 0:03:54
   --- ------------------------------------ 31.5/331.8 MB 1.3 MB/s eta 0:03:54
   --- ------------------------------------ 31.7/331.8 MB 1.3 MB/s eta 0:03:54
   --- ------------------------------------ 32.0/331.8 MB 1.3 MB/s eta 0:03:53
   --- ------------------------------------ 32.2/331.8 MB 1.3 MB/s eta 0:03:53
   --- ------------------------------------ 32.5/331.8 MB 1.3 MB/s eta 0:03:53
   --- ------------------------------------ 32.8/331.8 MB 1.3 MB/s eta 0:03:53
   --- ------------------------------------ 33.0/331.8 MB 1.3 MB/s eta 0:03:52
   ---- ----------------------------------- 33.3/331.8 MB 1.3 MB/s eta 0:03:52
   ---- ----------------------------------- 33.6/331.8 MB 1.3 MB/s eta 0:03:52
   ---- ----------------------------------- 33.8/331.8 MB 1.3 MB/s eta 0:03:52
   ---- ----------------------------------- 34.1/331.8 MB 1.3 MB/s eta 0:03:52
   ---- ----------------------------------- 34.6/331.8 MB 1.3 MB/s eta 0:03:51
   ---- ----------------------------------- 34.9/331.8 MB 1.3 MB/s eta 0:03:51
   ---- ----------------------------------- 35.1/331.8 MB 1.3 MB/s eta 0:03:51
   ---- ----------------------------------- 35.4/331.8 MB 1.3 MB/s eta 0:03:50
   ---- ----------------------------------- 35.7/331.8 MB 1.3 MB/s eta 0:03:50
   ---- ----------------------------------- 35.9/331.8 MB 1.3 MB/s eta 0:03:50
   ---- ----------------------------------- 36.2/331.8 MB 1.3 MB/s eta 0:03:50
   ---- ----------------------------------- 36.4/331.8 MB 1.3 MB/s eta 0:03:50
   ---- ----------------------------------- 36.7/331.8 MB 1.3 MB/s eta 0:03:49
   ---- ----------------------------------- 37.0/331.8 MB 1.3 MB/s eta 0:03:49
   ---- ----------------------------------- 37.2/331.8 MB 1.3 MB/s eta 0:03:49
   ---- ----------------------------------- 37.5/331.8 MB 1.3 MB/s eta 0:03:49
   ---- ----------------------------------- 37.7/331.8 MB 1.3 MB/s eta 0:03:49
   ---- ----------------------------------- 38.0/331.8 MB 1.3 MB/s eta 0:03:48
   ---- ----------------------------------- 38.3/331.8 MB 1.3 MB/s eta 0:03:48
   ---- ----------------------------------- 38.5/331.8 MB 1.3 MB/s eta 0:03:48
   ---- ----------------------------------- 38.8/331.8 MB 1.3 MB/s eta 0:03:48
   ---- ----------------------------------- 39.1/331.8 MB 1.3 MB/s eta 0:03:47
   ---- ----------------------------------- 39.3/331.8 MB 1.3 MB/s eta 0:03:47
   ---- ----------------------------------- 39.6/331.8 MB 1.3 MB/s eta 0:03:47
   ---- ----------------------------------- 39.8/331.8 MB 1.3 MB/s eta 0:03:47
   ---- ----------------------------------- 40.4/331.8 MB 1.3 MB/s eta 0:03:47
   ---- ----------------------------------- 40.6/331.8 MB 1.3 MB/s eta 0:03:47
   ---- ----------------------------------- 40.9/331.8 MB 1.3 MB/s eta 0:03:46
   ---- ----------------------------------- 41.2/331.8 MB 1.3 MB/s eta 0:03:46
   ---- ----------------------------------- 41.4/331.8 MB 1.3 MB/s eta 0:03:46
   ----- ---------------------------------- 41.7/331.8 MB 1.3 MB/s eta 0:03:46
   ----- ---------------------------------- 41.9/331.8 MB 1.3 MB/s eta 0:03:45
   ----- ---------------------------------- 42.2/331.8 MB 1.3 MB/s eta 0:03:45
   ----- ---------------------------------- 42.5/331.8 MB 1.3 MB/s eta 0:03:45
   ----- ---------------------------------- 42.7/331.8 MB 1.3 MB/s eta 0:03:45
   ----- ---------------------------------- 43.0/331.8 MB 1.3 MB/s eta 0:03:45
   ----- ---------------------------------- 43.3/331.8 MB 1.3 MB/s eta 0:03:44
   ----- ---------------------------------- 43.5/331.8 MB 1.3 MB/s eta 0:03:44
   ----- ---------------------------------- 43.8/331.8 MB 1.3 MB/s eta 0:03:44
   ----- ---------------------------------- 44.0/331.8 MB 1.3 MB/s eta 0:03:44
   ----- ---------------------------------- 44.3/331.8 MB 1.3 MB/s eta 0:03:44
   ----- ---------------------------------- 44.6/331.8 MB 1.3 MB/s eta 0:03:43
   ----- ---------------------------------- 44.8/331.8 MB 1.3 MB/s eta 0:03:43
   ----- ---------------------------------- 45.1/331.8 MB 1.3 MB/s eta 0:03:43
   ----- ---------------------------------- 45.4/331.8 MB 1.3 MB/s eta 0:03:43
   ----- ---------------------------------- 45.6/331.8 MB 1.3 MB/s eta 0:03:43
   ----- ---------------------------------- 45.9/331.8 MB 1.3 MB/s eta 0:03:42
   ----- ---------------------------------- 46.1/331.8 MB 1.3 MB/s eta 0:03:42
   ----- ---------------------------------- 46.4/331.8 MB 1.3 MB/s eta 0:03:42
   ----- ---------------------------------- 46.9/331.8 MB 1.3 MB/s eta 0:03:42
   ----- ---------------------------------- 47.2/331.8 MB 1.3 MB/s eta 0:03:42
   ----- ---------------------------------- 47.4/331.8 MB 1.3 MB/s eta 0:03:41
   ----- ---------------------------------- 47.7/331.8 MB 1.3 MB/s eta 0:03:41
   ----- ---------------------------------- 48.0/331.8 MB 1.3 MB/s eta 0:03:41

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\OneDrive\Desktop\Machine-Learning\.venv\Lib\site-packages\google\~upb'.
  You can safely remove it manually.
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\Users\\ANTARIKSHYA\\OneDrive\\Desktop\\Machine-Learning\\.venv\\Lib\\site-packages\\tensorflow\\python\\_pywrap_py_exception_registry.pyd'
Check the permissions.


[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import numpy as np
# import tensorflow as tf

print(f"NumPy version: {np.__version__}")
# print(f"TensorFlow version: {tf.__version__}")

NumPy version: 2.4.0

In [10]:
df = pd.read_csv(r"Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [14]:
df["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [15]:
df["Gender"].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [16]:
df.drop(columns=["RowNumber","CustomerId","Surname"],inplace=True)

In [17]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [25]:
pd.get_dummies(df,columns=["Geography","Gender"],drop_first=True,dtype = int)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0,0

In [31]:
X = df.drop(columns=["Exited"])
y = df["Exited"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [32]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [33]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [34]:
X_train.shape

(8000, 10)

In [36]:
# 1. Convert categories to numbers (ensure dtype=int)
df_final = pd.get_dummies(df, columns=["Geography", "Gender"], drop_first=True, dtype=int)

# 2. Define Features (X) and Target (y)
# We drop 'Exited' because it's what we want to predict
X = df_final.drop(columns=['Exited']) 
y = df_final['Exited']

# 3. Split the data (If you haven't already)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Now Scale
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaling successful!")

Scaling successful!

In [39]:
X_train_scaled

array([[ 0.35649971, -0.6557859 ,  0.34567966, ..., -0.57946723,
        -0.57638802,  0.91324755],
       [-0.20389777,  0.29493847, -0.3483691 , ...,  1.72572313,
        -0.57638802,  0.91324755],
       [-0.96147213, -1.41636539, -0.69539349, ..., -0.57946723,
         1.73494238,  0.91324755],
       ...,
       [ 0.86500853, -0.08535128, -1.38944225, ..., -0.57946723,
        -0.57638802, -1.09499335],
       [ 0.15932282,  0.3900109 ,  1.03972843, ..., -0.57946723,
        -0.57638802,  0.91324755],
       [ 0.47065475,  1.15059039, -1.38944225, ...,  1.72572313,
        -0.57638802,  0.91324755]], shape=(8000, 11))

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [43]:
# Run this in your code cell
!pip uninstall -y tensorflow keras keras-preprocessing tensorboard numpy
!pip cache purge
!pip install "numpy<2" "tensorflow<2.15"

Found existing installation: tensorflow 2.13.1
Uninstalling tensorflow-2.13.1:
  Successfully uninstalled tensorflow-2.13.1
Found existing installation: keras 3.13.2
Uninstalling keras-3.13.2:
  Successfully uninstalled keras-3.13.2
Found existing installation: tensorboard 2.20.0
Uninstalling tensorboard-2.20.0:
  Successfully uninstalled tensorboard-2.20.0
Found existing installation: numpy 2.4.2
Uninstalling numpy-2.4.2:
  Successfully uninstalled numpy-2.4.2

WARNING: Skipping keras-preprocessing as it is not installed.

Files removed: 1526 (1253.8 MB)
Collecting numpy<2
  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Collecting tensorflow<2.15
  Downloading tensorflow-2.14.1-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
Collecting tensorflow-intel==2.14.1 (from tensorflow<2.15)
  Downloading tensorflow_intel-2.14.1-cp311-cp311-win_amd64.whl.metadata (4.8 kB)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (3.15.1)
Requirement already satisfied: libclang>=13.0.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (18.1.1)
Collecting ml-dtypes==0.2.0 (from tensorflow-intel==2.14.1->tensorflow<2.15)
  Downloading ml_dtypes-0.2.0-cp311-cp311-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (3.4.0)
Requirement already satisfied: packaging in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (25.0)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow-intel==2.14.1->tensorflow<2.15)
  Downloading protobuf-4.25.8-cp310-abi3-win_amd64.whl.metadata (541 bytes)
Requirement already satisfied: setuptools in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (4.15.0)
Collecting wrapt<1.15,>=1.11.0 (from tensorflow-intel==2.14.1->tensorflow<2.15)
  Downloading wrapt-1.14.2-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (0.31.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorflow-intel==2.14.1->tensorflow<2.15) (1.74.0)
Collecting tensorboard<2.15,>=2.14 (from tensorflow-intel==2.14.1->tensorflow<2.15)
  Downloading tensorboard-2.14.1-py3-none-any.whl.metadata (1.7 kB)
Collecting tensorflow-estimator<2.15,>=2.14.0 (from tensorflow-intel==2.14.1->tensorflow<2.15)
  Downloading tensorflow_estimator-2.14.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting keras<2.15,>=2.14.0 (from tensorflow-intel==2.14.1->tensorflow<2.15)
  Downloading keras-2.14.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (2.48.0)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (3.10.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (2.32.5)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (3.1.5)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (46.0.4)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (2025.11.12)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from rsa<5,>=3.1.4->google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (0.6.2)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.14.1->tensorflow<2.15) (0.45.1)
Requirement already satisfied: cffi>=2.0.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (2.0.0)
Requirement already satisfied: pycparser in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (2.23)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (3.3.1)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\antarikshya\onedrive\desktop\machine-learning\.venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.1->tensorflow<2.15) (3.0.3)
Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/15.8 MB 1.3 MB/s eta 0:00:12
   - -------------------------------------- 0.8/15.8 MB 1.3 MB/s eta 0:00:12
   -- ------------------------------------- 1.0/15.8 MB 1.3 MB/s eta 0:00:12
   --- ------------------------------------ 1.3/15.8 MB 1.3 MB/s eta 0:00:12
   --- ------------------------------------ 1.6/15.8 MB 1.3 MB/s eta 0:00:12
   ---- ----------------------------------- 1.8/15.8 MB 1.3 MB/s eta 0:00:11
   ----- ---------------------------------- 2.1/15.8 MB 1.3 MB/s eta 0:00:11
   ----- ---------------------------------- 2.4/15.8 MB 1.3 MB/s eta 0:00:11
   ------ --------------------------------- 2.6/15.8 MB 1.3 MB/s eta 0:00:11
   ------- -------------------------------- 2.9/15.8 MB 1.3 MB/s eta 0:00:11
   ------- -------------------------------- 3.1/15.8 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.4/15.8 MB 1.3 MB/s eta 0:00:10
   --------- ------------------------------ 3.7/15.8 MB 1.3 MB/s eta 0:00:10
   --------- ------------------------------ 3.9/15.8 MB 1.3 MB/s eta 0:00:10
   ---------- ----------------------------- 4.2/15.8 MB 1.3 MB/s eta 0:00:10
   ----------- ---------------------------- 4.5/15.8 MB 1.3 MB/s eta 0:00:09
   ----------- ---------------------------- 4.7/15.8 MB 1.3 MB/s eta 0:00:09
   ------------ --------------------------- 5.0/15.8 MB 1.3 MB/s eta 0:00:09
   ------------- -------------------------- 5.2/15.8 MB 1.3 MB/s eta 0:00:09
   ------------- -------------------------- 5.5/15.8 MB 1.3 MB/s eta 0:00:08
   -------------- ------------------------- 5.8/15.8 MB 1.3 MB/s eta 0:00:08
   --------------- ------------------------ 6.0/15.8 MB 1.3 MB/s eta 0:00:08
   --------------- ------------------------ 6.3/15.8 MB 1.3 MB/s eta 0:00:08
   ---------------- ----------------------- 6.6/15.8 MB 1.3 MB/s eta 0:00:08
   ----------------- ---------------------- 6.8/15.8 MB 1.3 MB/s eta 0:00:07
   ----------------- ---------------------- 7.1/15.8 MB 1.3 MB/s eta 0:00:07
   ------------------ --------------------- 7.3/15.8 MB 1.3 MB/s eta 0:00:07
   ------------------- -------------------- 7.6/15.8 MB 1.3 MB/s eta 0:00:07
   -------------------- ------------------- 8.1/15.8 MB 1.3 MB/s eta 0:00:06
   --------------------- ------------------ 8.4/15.8 MB 1.3 MB/s eta 0:00:06
   --------------------- ------------------ 8.7/15.8 MB 1.3 MB/s eta 0:00:06
   ---------------------- ----------------- 8.9/15.8 MB 1.3 MB/s eta 0:00:06
   ----------------------- ---------------- 9.2/15.8 MB 1.3 MB/s eta 0:00:06
   ----------------------- ---------------- 9.4/15.8 MB 1.3 MB/s eta 0:00:05
   ------------------------ --------------- 9.7/15.8 MB 1.3 MB/s eta 0:00:05
   ------------------------- -------------- 10.0/15.8 MB 1.3 MB/s eta 0:00:05
   ------------------------- -------------- 10.2/15.8 MB 1.3 MB/s eta 0:00:05
   -------------------------- ------------- 10.5/15.8 MB 1.3 MB/s eta 0:00:05
   --------------------------- ------------ 10.7/15.8 MB 1.3 MB/s eta 0:00:04
   --------------------------- ------------ 11.0/15.8 MB 1.3 MB/s eta 0:00:04
   ---------------------------- ----------- 11.3/15.8 MB 1.3 MB/s eta 0:00:04
   ----------------------------- ---------- 11.5/15.8 MB 1.3 MB/s eta 0:00:04
   ----------------------------- ---------- 11.8/15.8 MB 1.3 MB/s eta 0:00:04
   ------------------------------ --------- 12.1/15.8 MB 1.3 MB/s eta 0:00:03
   ------------------------------- -------- 12.3/15.8 MB 1.3 MB/s eta 0:00:03
   ------------------------------- -------- 12.6/15.8 MB 1.3 MB/s eta 0:00:03
   -------------------------------- ------- 12.8/15.8 MB 1.3 MB/s eta 0:00:03
   --------------------------------- ------ 13.1/15.8 MB 1.3 MB/s eta 0:00:03
   --------------------------------- ------ 13.4/15.8 MB 1.3 MB/s eta 0:00:02
   ---------------------------------- ----- 13.6/15.8 MB 1.3 MB/s eta 0:00:02
   ----------------------------------- ---- 13.9/15.8 MB 1.3 MB/s eta 0:00:02
   ----------------------------------- ---- 14.2/15.8 MB 1.3 MB/s eta 0:00:02
   ------------------------------------ --- 14.4/15.8 MB 1.3 MB/s eta 0:00:02
   ------------------------------------- -- 14.7/15.8 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 14.9/15.8 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 15.2/15.8 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  15.5/15.8 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  15.7/15.8 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 15.8/15.8 MB 1.3 MB/s  0:00:12
Downloading tensorflow-2.14.1-cp311-cp311-win_amd64.whl (2.1 kB)
Downloading tensorflow_intel-2.14.1-cp311-cp311-win_amd64.whl (284.2 MB)
   ---------------------------------------- 0.0/284.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/284.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/284.2 MB ? eta -:--:--
   ---------------------------------------- 0.8/284.2 MB 1.3 MB/s eta 0:03:40
   ---------------------------------------- 1.0/284.2 MB 1.1 MB/s eta 0:04:08
   ---------------------------------------- 1.3/284.2 MB 1.3 MB/s eta 0:03:36
   ---------------------------------------- 1.6/284.2 MB 1.3 MB/s eta 0:03:36
   ---------------------------------------- 1.8/284.2 MB 1.3 MB/s eta 0:03:36
   ---------------------------------------- 2.1/284.2 MB 1.3 MB/s eta 0:03:39
   ---------------------------------------- 2.4/284.2 MB 1.3 MB/s eta 0:03:39
   ---------------------------------------- 2.6/284.2 MB 1.3 MB/s eta 0:03:39
   ---------------------------------------- 2.9/284.2 MB 1.3 MB/s eta 0:03:38
   ---------------------------------------- 3.1/284.2 MB 1.3 MB/s eta 0:03:38
   ---------------------------------------- 3.4/284.2 MB 1.3 MB/s eta 0:03:39
    --------------------------------------- 3.7/284.2 MB 1.3 MB/s eta 0:03:38
    --------------------------------------- 3.9/284.2 MB 1.3 MB/s eta 0:03:39
    --------------------------------------- 4.2/284.2 MB 1.3 MB/s eta 0:03:37
    --------------------------------------- 4.5/284.2 MB 1.3 MB/s eta 0:03:38
    --------------------------------------- 4.7/284.2 MB 1.3 MB/s eta 0:03:38
    --------------------------------------- 5.0/284.2 MB 1.3 MB/s eta 0:03:38
    --------------------------------------- 5.2/284.2 MB 1.3 MB/s eta 0:03:38
    --------------------------------------- 5.5/284.2 MB 1.3 MB/s eta 0:03:37
    --------------------------------------- 5.8/284.2 MB 1.3 MB/s eta 0:03:37
    --------------------------------------- 6.0/284.2 MB 1.3 MB/s eta 0:03:37
    --------------------------------------- 6.3/284.2 MB 1.3 MB/s eta 0:03:37
    --------------------------------------- 6.6/284.2 MB 1.3 MB/s eta 0:03:37
    --------------------------------------- 6.8/284.2 MB 1.3 MB/s eta 0:03:37
    --------------------------------------- 7.1/284.2 MB 1.3 MB/s eta 0:03:36
   - -------------------------------------- 7.3/284.2 MB 1.3 MB/s eta 0:03:36
   - -------------------------------------- 7.6/284.2 MB 1.3 MB/s eta 0:03:35
   - -------------------------------------- 7.9/284.2 MB 1.3 MB/s eta 0:03:36
   - -------------------------------------- 8.1/284.2 MB 1.3 MB/s eta 0:03:36
   - -------------------------------------- 8.4/284.2 MB 1.3 MB/s eta 0:03:35
   - -------------------------------------- 8.7/284.2 MB 1.3 MB/s eta 0:03:35
   - -------------------------------------- 8.9/284.2 MB 1.3 MB/s eta 0:03:35
   - -------------------------------------- 9.2/284.2 MB 1.3 MB/s eta 0:03:35
   - -------------------------------------- 9.4/284.2 MB 1.3 MB/s eta 0:03:34
   - -------------------------------------- 9.7/284.2 MB 1.3 MB/s eta 0:03:34
   - -------------------------------------- 10.0/284.2 MB 1.3 MB/s eta 0:03:34
   - -------------------------------------- 10.2/284.2 MB 1.3 MB/s eta 0:03:34
   - -------------------------------------- 10.5/284.2 MB 1.3 MB/s eta 0:03:33
   - -------------------------------------- 10.7/284.2 MB 1.3 MB/s eta 0:03:34
   - -------------------------------------- 11.0/284.2 MB 1.3 MB/s eta 0:03:33
   - -------------------------------------- 11.3/284.2 MB 1.3 MB/s eta 0:03:34
   - -------------------------------------- 11.5/284.2 MB 1.3 MB/s eta 0:03:33
   - -------------------------------------- 11.8/284.2 MB 1.3 MB/s eta 0:03:33
   - -------------------------------------- 12.1/284.2 MB 1.3 MB/s eta 0:03:33
   - -------------------------------------- 12.3/284.2 MB 1.3 MB/s eta 0:03:33
   - -------------------------------------- 12.6/284.2 MB 1.3 MB/s eta 0:03:32
   - -------------------------------------- 12.8/284.2 MB 1.3 MB/s eta 0:03:32
   - -------------------------------------- 13.1/284.2 MB 1.3 MB/s eta 0:03:32
   - -------------------------------------- 13.4/284.2 MB 1.3 MB/s eta 0:03:32
   - -------------------------------------- 13.6/284.2 MB 1.3 MB/s eta 0:03:32
   - -------------------------------------- 13.6/284.2 MB 1.3 MB/s eta 0:03:32
   - -------------------------------------- 13.9/284.2 MB 1.3 MB/s eta 0:03:36
   - -------------------------------------- 14.2/284.2 MB 1.3 MB/s eta 0:03:35
   -- ------------------------------------- 14.4/284.2 MB 1.3 MB/s eta 0:03:35
   -- ------------------------------------- 14.7/284.2 MB 1.3 MB/s eta 0:03:35
   -- ------------------------------------- 14.9/284.2 MB 1.3 MB/s eta 0:03:34
   -- ------------------------------------- 15.2/284.2 MB 1.3 MB/s eta 0:03:34
   -- ------------------------------------- 15.5/284.2 MB 1.3 MB/s eta 0:03:34
   -- ------------------------------------- 15.7/284.2 MB 1.3 MB/s eta 0:03:33
   -- ------------------------------------- 15.7/284.2 MB 1.3 MB/s eta 0:03:33
   -- ------------------------------------- 16.0/284.2 MB 1.2 MB/s eta 0:03:38
   -- ------------------------------------- 16.3/284.2 MB 1.2 MB/s eta 0:03:37
   -- ------------------------------------- 16.5/284.2 MB 1.2 MB/s eta 0:03:37
   -- ------------------------------------- 16.8/284.2 MB 1.2 MB/s eta 0:03:37
   -- ------------------------------------- 17.0/284.2 MB 1.2 MB/s eta 0:03:37
   -- ------------------------------------- 17.3/284.2 MB 1.2 MB/s eta 0:03:36
   -- ------------------------------------- 17.6/284.2 MB 1.2 MB/s eta 0:03:36
   -- ------------------------------------- 17.8/284.2 MB 1.2 MB/s eta 0:03:37
   -- ------------------------------------- 18.1/284.2 MB 1.2 MB/s eta 0:03:35
   -- ------------------------------------- 18.4/284.2 MB 1.2 MB/s eta 0:03:35
   -- ------------------------------------- 18.6/284.2 MB 1.2 MB/s eta 0:03:35
   -- ------------------------------------- 18.9/284.2 MB 1.2 MB/s eta 0:03:34
   -- ------------------------------------- 19.1/284.2 MB 1.2 MB/s eta 0:03:34
   -- ------------------------------------- 19.4/284.2 MB 1.2 MB/s eta 0:03:34
   -- ------------------------------------- 19.7/284.2 MB 1.2 MB/s eta 0:03:34
   -- ------------------------------------- 19.9/284.2 MB 1.2 MB/s eta 0:03:33

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\AppData\Local\Temp\pip-uninstall-0m9pgvv1'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\OneDrive\Desktop\Machine-Learning\.venv\Lib\site-packages\tensorflow\python\~lient'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\OneDrive\Desktop\Machine-Learning\.venv\Lib\site-packages\tensorflow\python\~ramework'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\OneDrive\Desktop\Machine-Learning\.venv\Lib\site-packages\tensorflow\python\~ib'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\OneDrive\Desktop\Machine-Learning\.venv\Lib\site-packages\tensorflow\python\~latform'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\OneDrive\Desktop\Machine-Learning\.venv\Lib\site-packages\tensorflow\python\~til'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\OneDrive\Desktop\Machine-Learning\.venv\Lib\site-packages\tensorflow\~sl'.
  You can safely remove it manually.

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [47]:
!pip install --upgrade --force-reinstall ml_dtypes
import numpy as np
import tensorflow as tf

model = Sequential()

model.add(Dense(3,activation="sigmoid",input_dim=11))
model.add(Dense(1,activation="sigmoid"))

Collecting ml_dtypes
  Downloading ml_dtypes-0.5.4-cp311-cp311-win_amd64.whl.metadata (9.2 kB)
Collecting numpy>=1.21 (from ml_dtypes)
  Downloading numpy-2.4.2-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Downloading ml_dtypes-0.5.4-cp311-cp311-win_amd64.whl (210 kB)
Downloading numpy-2.4.2-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 1.3 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.6 MB 1.3 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/12.6 MB 1.3 MB/s eta 0:00:09
   ---- ----------------------------------- 1.3/12.6 MB 1.3 MB/s eta 0:00:09
   ---- ----------------------------------- 1.6/12.6 MB 1.3 MB/s eta 0:00:09
   ----- ---------------------------------- 1.8/12.6 MB 1.3 MB/s eta 0:00:09
   ------ --------------------------------- 2.1/12.6 MB 1.3 MB/s eta 0:00:09
   ------- -------------------------------- 2.4/12.6 MB 1.3 MB/s eta 0:00:08
   -------- ------------------------------- 2.6/12.6 MB 1.3 MB/s eta 0:00:08
   --------- ------------------------------ 2.9/12.6 MB 1.3 MB/s eta 0:00:08
   --------- ------------------------------ 3.1/12.6 MB 1.3 MB/s eta 0:00:08
   ---------- ----------------------------- 3.4/12.6 MB 1.3 MB/s eta 0:00:08
   ----------- ---------------------------- 3.7/12.6 MB 1.3 MB/s eta 0:00:07
   ------------ --------------------------- 3.9/12.6 MB 1.3 MB/s eta 0:00:07
   ------------- -------------------------- 4.2/12.6 MB 1.3 MB/s eta 0:00:07
   -------------- ------------------------- 4.5/12.6 MB 1.3 MB/s eta 0:00:07
   -------------- ------------------------- 4.7/12.6 MB 1.3 MB/s eta 0:00:07
   --------------- ------------------------ 5.0/12.6 MB 1.3 MB/s eta 0:00:07
   ---------------- ----------------------- 5.2/12.6 MB 1.2 MB/s eta 0:00:07
   ---------------- ----------------------- 5.2/12.6 MB 1.2 MB/s eta 0:00:07
   ----------------- ---------------------- 5.5/12.6 MB 1.2 MB/s eta 0:00:07
   ----------------- ---------------------- 5.5/12.6 MB 1.2 MB/s eta 0:00:07
   ------------------ --------------------- 5.8/12.6 MB 1.1 MB/s eta 0:00:06
   ------------------- -------------------- 6.0/12.6 MB 1.1 MB/s eta 0:00:06
   ------------------- -------------------- 6.3/12.6 MB 1.1 MB/s eta 0:00:06
   ------------------- -------------------- 6.3/12.6 MB 1.1 MB/s eta 0:00:06
   -------------------- ------------------- 6.6/12.6 MB 1.1 MB/s eta 0:00:06
   --------------------- ------------------ 6.8/12.6 MB 1.1 MB/s eta 0:00:06
   ---------------------- ----------------- 7.1/12.6 MB 1.1 MB/s eta 0:00:06
   ----------------------- ---------------- 7.3/12.6 MB 1.1 MB/s eta 0:00:05
   ----------------------- ---------------- 7.3/12.6 MB 1.1 MB/s eta 0:00:05
   ------------------------ --------------- 7.6/12.6 MB 1.1 MB/s eta 0:00:05
   ------------------------ --------------- 7.9/12.6 MB 1.1 MB/s eta 0:00:05
   ------------------------- -------------- 8.1/12.6 MB 1.1 MB/s eta 0:00:05
   -------------------------- ------------- 8.4/12.6 MB 1.1 MB/s eta 0:00:04
   -------------------------- ------------- 8.4/12.6 MB 1.1 MB/s eta 0:00:04
   --------------------------- ------------ 8.7/12.6 MB 1.1 MB/s eta 0:00:04
   ---------------------------- ----------- 8.9/12.6 MB 1.1 MB/s eta 0:00:04
   ----------------------------- ---------- 9.2/12.6 MB 1.1 MB/s eta 0:00:04
   ----------------------------- ---------- 9.4/12.6 MB 1.1 MB/s eta 0:00:03
   ------------------------------ --------- 9.7/12.6 MB 1.1 MB/s eta 0:00:03
   ------------------------------- -------- 10.0/12.6 MB 1.1 MB/s eta 0:00:03
   -------------------------------- ------- 10.2/12.6 MB 1.1 MB/s eta 0:00:03
   --------------------------------- ------ 10.5/12.6 MB 1.1 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.6 MB 1.1 MB/s eta 0:00:02
   ---------------------------------- ----- 11.0/12.6 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 11.3/12.6 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 11.5/12.6 MB 1.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 1.1 MB/s  0:00:11
Installing collected packages: numpy, ml_dtypes

  Attempting uninstall: numpy

    Found existing installation: numpy 1.26.4

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
    Uninstalling numpy-1.26.4:
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
      Successfully uninstalled numpy-1.26.4
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
  Attempting uninstall: ml_dtypes
   ---------------------------------------- 0/2 [numpy]
    Found existing installation: ml-dtypes 0.2.0
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [ml_dtypes]
    Uninstalling ml-dtypes-0.2.0:
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
      Successfully uninstalled ml-dtypes-0.2.0
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]
   -------------------- ------------------- 1/2 [ml_dtypes]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\OneDrive\Desktop\Machine-Learning\.venv\Lib\site-packages\~-mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\OneDrive\Desktop\Machine-Learning\.venv\Lib\site-packages\~-mpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\ANTARIKSHYA\OneDrive\Desktop\Machine-Learning\.venv\Lib\site-packages\~l_dtypes'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.14.1 requires ml-dtypes==0.2.0, but you have ml-dtypes 0.5.4 which is incompatible.
tensorflow-intel 2.14.1 requires numpy<2.0.0,>=1.23.5, but you have numpy 2.4.2 which is incompatible.

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle

In [ ]:
model.summary()

In [ ]:
model.compile(loss="binary_crossentropy",optimizer="Adam",metrics="Accuracy")

In [48]:
history = model.fit(X_train_scaled,y_train,epochs=100,validation_split=0.2)

NameError: name 'model' is not defined

In [ ]:
model.layers[0].get_weights()

In [ ]:
model.layers[1].get_weights()

In [ ]:
y_log = model.predict(X_test_scaled)

In [ ]:
y_pred = np.where(y_log>0.1,1,0)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

In [49]:
history.history

NameError: name 'history' is not defined

In [50]:
plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])

NameError: name 'history' is not defined

In [51]:
plt.plot(history.history["accuracy"])
plt.plot(history.history["val_accuracy"])

NameError: name 'history' is not defined