# Text Pre-processing

In [21]:
import numpy as np
import pandas as pd

In [29]:
import pandas as pd

df = pd.read_csv("IMDB Dataset.csv", engine='python', on_bad_lines='warn')

/tmp/ipython-input-1431871211.py:3: ParserWarning: Skipping line 22152: unexpected end of data

  df = pd.read_csv("IMDB Dataset.csv", engine='python', on_bad_lines='warn')

## LowerCasing

In [30]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
22145  Rich, alcoholic Robert Stack falls in love wit...  positive
22146  In an era of such awful cartoons, I am rather ...  positive
22147  Well, at least this was the last sequel that I...  negative
22148  Oh my God... where to begin? "Chupacabra Terro...  negative
22149  This movie is extremely boring, it tells a sto...  negative

[22150 rows x 2 columns]

In [31]:
df["review"].str.lower()

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
22145    rich, alcoholic robert stack falls in love wit...
22146    in an era of such awful cartoons, i am rather ...
22147    well, at least this was the last sequel that i...
22148    oh my god... where to begin? "chupacabra terro...
22149    this movie is extremely boring, it tells a sto...
Name: review, Length: 22150, dtype: object

In [33]:
df["review"] = df["review"].str.lower()

In [36]:
df.sample(5)

                                                  review sentiment
7600   i chose "dead creatures" because i thought it ...  negative
5999   few movies can be viewed almost 60 years later...  positive
18298  this two disc set is incredible! if you're lik...  positive
7674   this, in my opinion, is a very poor movie that...  negative
10683  i still can't describe what to feel when i rec...  positive

## Removing HTML

In [37]:
import re
def striphtml(data):
  p = re.compile(r'<.*?>')
  return p.sub('',data)

In [40]:
df['review'] = df['review'].apply(striphtml)

In [41]:
df["review"]

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
22145    rich, alcoholic robert stack falls in love wit...
22146    in an era of such awful cartoons, i am rather ...
22147    well, at least this was the last sequel that i...
22148    oh my god... where to begin? "chupacabra terro...
22149    this movie is extremely boring, it tells a sto...
Name: review, Length: 22150, dtype: object

# Removing URLs

In [42]:
text1 = "Check Out my Notebook https://www.kaggle.com/campusx/notebook8223fc1abb"
text2 = "Check Out my Notebook https://www.kaggle.com/campusx/notebook8223fc1abb"
text3 = "Check Out Google https://www.google.com"

In [46]:
text1 = re.sub(r'https?://\S+|www\.\S+', '', text1)
text2 = re.sub(r'https?://\S+|www\.\S+', '', text2)
text3 = re.sub(r'https?://\S+|www\.\S+', '', text3)

In [47]:
text1

'Check Out my Notebook '

## Removing Punctuations

In [54]:
import string  # For punctuation, whitespace, etc.
import time    # For handling time-related tasks

# Now you can use them:
print(string.punctuation)
print(time.ctime())

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
Tue Feb 10 15:05:01 2026

In [56]:
exclude = string.punctuation

In [57]:
def remove_punc(text):
  for char in exclude:
    text = text.replace(char,'')
    return text

In [68]:
text = "string. With. Punctuation?"

In [69]:
start = time.time()
print(remove_punc(text))
time1 = time.time() - start
print(time1*50000)

string. With. Punctuation?
9.202957153320312

In [70]:
def remove_punc1(text):
  return text.translate(str.maketrans('','',exclude))

In [71]:
start = time.time()
print(remove_punc1(text))
time2 = time.time() - start
print(time2)

string With Punctuation
0.00020813941955566406

In [73]:
time1/time2 * 100

88.43069873997709

In [74]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
22145  rich, alcoholic robert stack falls in love wit...  positive
22146  in an era of such awful cartoons, i am rather ...  positive
22147  well, at least this was the last sequel that i...  negative
22148  oh my god... where to begin? "chupacabra terro...  negative
22149  this movie is extremely boring, it tells a sto...  negative

[22150 rows x 2 columns]

In [75]:
df['review'] = df['review'].apply(remove_punc1)

In [76]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
22145  rich alcoholic robert stack falls in love with...  positive
22146  in an era of such awful cartoons i am rather i...  positive
22147  well at least this was the last sequel that i ...  negative
22148  oh my god where to begin chupacabra terror is ...  negative
22149  this movie is extremely boring it tells a stor...  negative

[22150 rows x 2 columns]

## Chat Word Treatment

In [84]:

DB = """
A3=Anytime, Anywhere, Anyplace
ADIH=Another Day In Hell
AFK=Away From Keyboard
AFAIK=As Far As I Know
ASAP=As Soon As Possible
ASL=Age, Sex, Location
ATK=At The Keyboard
ATM=At The Moment
BAE=Before Anyone Else
BAK=Back At Keyboard
BBL=Be Back Later
BBS=Be Back Soon
BFN=Bye For Now
B4N=Bye For Now
BRB=Be Right Back
BRUH=Bro
BRT=Be Right There
BSAAW=Big Smile And A Wink
BTW=By The Way
BWL=Bursting With Laughter
CSL=Can’t Stop Laughing
CU=See You
CUL8R=See You Later
CYA=See You
DM=Direct Message
FAQ=Frequently Asked Questions
FC=Fingers Crossed
FIMH=Forever In My Heart
FOMO=Fear Of Missing Out
FR=For Real
FWIW=For What It's Worth
FYP=For You Page
FYI=For Your Information
G9=Genius
GAL=Get A Life
GG=Good Game
GMTA=Great Minds Think Alike
GN=Good Night
GOAT=Greatest Of All Time
GR8=Great!
HBD=Happy Birthday
IC=I See
ICQ=I Seek You
IDC=I Don’t Care
IDK=I Don't Know
IFYP=I Feel Your Pain
ILU=I Love You
ILY=I Love You
IMHO=In My Honest/Humble Opinion
IMU=I Miss You
IMO=In My Opinion
IOW=In Other Words
IRL=In Real Life
IYKYK=If You Know, You Know
JK=Just Kidding
KISS=Keep It Simple, Stupid
L=Loss
L8R=Later
LDR=Long Distance Relationship
LMK=Let Me Know
LMAO=Laughing My A** Off
LOL=Laughing Out Loud
LTNS=Long Time No See
M8=Mate
MFW=My Face When
MID=Mediocre
MRW=My Reaction When
MTE=My Thoughts Exactly
NVM=Never Mind
NRN=No Reply Necessary
NPC=Non-Player Character
OIC=Oh I See
OP=Overpowered
PITA=Pain In The A**
POV=Point Of View
PRT=Party
PRW=Parents Are Watching
ROFL=Rolling On The Floor Laughing
ROFLOL=Rolling On The Floor Laughing Out Loud
ROTFLMAO=Rolling On The Floor Laughing My A** Off
RN=Right Now
SK8=Skate
STATS=Your Sex And Age
SUS=Suspicious
TBH=To Be Honest
TFW=That Feeling When
THX=Thank You
TIME=Tears In My Eyes
TLDR=Too Long, Didn’t Read
TNTL=Trying Not To Laugh
TTFN=Ta-Ta For Now!
TTYL=Talk To You Later
U=You
U2=You Too
U4E=Yours For Ever
W=Win
W8=Wait...
WB=Welcome Back
WTF=What The F**k
WTG=Way To Go!
WUF=Where Are You From?
WYD=What You Doing?
WYWH=Wish You Were Here
ZZZ=Sleeping, Bored, Tired """

In [85]:
slang_dict = {
    line.split('=')[0].strip(): line.split('=')[1].strip()
    for line in DB.strip().splitlines()
    if '=' in line
}

In [86]:
def translator(user_string):
    # Standardize whitespace and split into words
    words = user_string.split()
    new_words = []

    for word in words:
        # Remove punctuation to match the dictionary key
        # e.g., "ASAP!" becomes "ASAP"
        clean_word = re.sub(r'[^\w]', '', word).upper()

        # Look up in dictionary, keep original if not found
        translated = slang_dict.get(clean_word, word)
        new_words.append(translated)

    return ' '.join(new_words)

In [87]:
translator("IMHO He is really Selfish")

'In My Honest/Humble Opinion He is really Selfish'

## Spelling Checking

In [93]:
incorrect_text = "ceertrain conditionas diriing several geneeratons aree modifiied in the samee maner"

In [94]:
from textblob import TextBlob

In [98]:
textBlb = TextBlob(incorrect_text)
textBlb.correct().string

'certain conditions during several generations are modified in the same manner'

## Removing StopWords

In [104]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [110]:
stopwords.words("english")

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [111]:
def remove_stopwords(text):
  new_text = []
  for word in text.split():
    if word in stopwords.words("english"):
      new_text.append('')
    else:
      new_text.append(word)
  x = new_text[:]
  new_text.clear()
  return " ".join(x)

In [112]:
df["review"].apply(remove_stopwords)

KeyboardInterrupt:

In [ ]:
df.sample(5)

## Handling Emojis

In [114]:
!pip install emoji
import emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 10.6 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0
This movie was an absolute masterpiece! :clapper_board: The acting was top-tier and the plot twist caught me off guard. :exploding_head: 10/10 would watch again! :sparkles:

In [115]:
print(emoji.demojize("This movie was an absolute masterpiece! 🎬 The acting was top-tier and the plot twist caught me off guard. 🤯 10/10 would watch again! ✨"))

This movie was an absolute masterpiece! :clapper_board: The acting was top-tier and the plot twist caught me off guard. :exploding_head: 10/10 would watch again! :sparkles:

# Tokenization